<?php

return [
    'access' => [
        'category'=>[
            'list-category'=>'category_List',
            'add-category'=>'category_Add',
            'edit-category'=>'category_Edit',
            'delete-category'=>'category_Delete',
        ],
        'product'=>[
            'list-product'=>'products_List',
            'add-product'=>'products_Add',
            'edit-product'=>'products_Edit',
            'delete-product'=>'products_Delete',
        ],
        'user_list'=>[
            'list-user'=>'user_List',
            'edit-user'=>'user_Edit',
            'delete-user'=>'user_Delete',
        ],
        'role'=>[
            'list-role'=>'role_List',
            'add-role'=>'role_Add',
            'edit-role'=>'role_Edit',
            'delete-role'=>'role_Delete',
        ],
        'permission'=>[
            'add-permission'=>'permission_Add',
        ],
    ],
    'table_module'=>[
        'category',
        'products',
        'user',
        'role',
        'permission',
    ],
    'module_childrent'=>[
        'List',
        'Add',
        'Edit',
        'Delete'
    ]
];
